[package]
name = "command_line_worker"
version = "0.1.0"
authors = [
  "Valentin Noel <valentin.noel@media-io.com>",
  "Marc-Antoine Arnaud <maarnaud@media-io.com>"
]
edition = "2018"

[dependencies]
amqp_worker = "0.9"
lapin-futures = "0.28.4"
log = "0.4"
semver = "0.9"
