[package]
name = "command_line_worker"
version = "0.1.3"
authors = [
  "Valentin Noel <valentin.noel@media-io.com>",
  "Marc-Antoine Arnaud <maarnaud@media-io.com>"
]
edition = "2018"

[dependencies]
mcai_worker_sdk = "0.10"

[build-dependencies]
built = "0.4"
